-- V2: Catálogo de productos de la cafetería
CREATE TABLE productos (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    precio          DOUBLE PRECISION NOT NULL,
    categoria       VARCHAR(80) NOT NULL,
    descripcion     VARCHAR(500),
    fecha_creacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_productos_precio CHECK (precio >= 0)
);

CREATE INDEX idx_productos_categoria ON productos (categoria);
CREATE INDEX idx_productos_activo ON productos (activo);

COMMENT ON TABLE productos IS 'Menú / productos vendibles';
