-- V3: Proveedores de insumos
CREATE TABLE proveedores (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(150) NOT NULL,
    telefono    VARCHAR(30) NOT NULL,
    direccion   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    activo      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_proveedores_email UNIQUE (email)
);

CREATE INDEX idx_proveedores_activo ON proveedores (activo);

COMMENT ON TABLE proveedores IS 'Empresas que proveen insumos al inventario';
