-- V4: Inventario de insumos (relacionado con proveedor)
CREATE TABLE inventario (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_insumo       VARCHAR(150) NOT NULL,
    cantidad            INTEGER NOT NULL DEFAULT 0,
    unidad              VARCHAR(30) NOT NULL,
    stock_minimo        INTEGER NOT NULL DEFAULT 0,
    precio_unitario     NUMERIC(10, 2) NOT NULL,
    proveedor_id        INTEGER NOT NULL,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventario_proveedor
        FOREIGN KEY (proveedor_id) REFERENCES proveedores (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_inventario_cantidad CHECK (cantidad >= 0),
    CONSTRAINT ck_inventario_stock_minimo CHECK (stock_minimo >= 0),
    CONSTRAINT ck_inventario_precio CHECK (precio_unitario >= 0)
);

CREATE INDEX idx_inventario_proveedor ON inventario (proveedor_id);
CREATE INDEX idx_inventario_nombre ON inventario (nombre_insumo);

COMMENT ON TABLE inventario IS 'Stock de insumos; API actual envía nombre de proveedor, en BD se usa proveedor_id';
