-- V5: Pedidos y líneas de detalle
CREATE TABLE pedidos (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente         VARCHAR(150) NOT NULL,
    estado          VARCHAR(30) NOT NULL DEFAULT 'pendiente',
    total           NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_creacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pedidos_total CHECK (total >= 0),
    CONSTRAINT ck_pedidos_estado CHECK (
        estado IN ('pendiente', 'en_proceso', 'completado', 'cancelado')
    )
);

CREATE TABLE detalle_pedido (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       INTEGER NOT NULL,
    producto_id     INTEGER NOT NULL,
    cantidad        INTEGER NOT NULL,
    precio          NUMERIC(10, 2) NOT NULL,
    subtotal        NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_detalle_pedido_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_detalle_pedido_producto
        FOREIGN KEY (producto_id) REFERENCES productos (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_precio CHECK (precio >= 0),
    CONSTRAINT ck_detalle_subtotal CHECK (subtotal >= 0),
    CONSTRAINT uk_detalle_pedido_producto UNIQUE (pedido_id, producto_id)
);

CREATE INDEX idx_pedidos_estado ON pedidos (estado);
CREATE INDEX idx_pedidos_cliente ON pedidos (cliente);
CREATE INDEX idx_detalle_pedido_pedido ON detalle_pedido (pedido_id);

COMMENT ON TABLE detalle_pedido IS 'Líneas de un pedido; un producto una vez por pedido';
