-- V6: Ventas registradas por usuario
CREATE TABLE ventas (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      INTEGER NOT NULL,
    producto_id     INTEGER NOT NULL,
    cantidad        INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    total           NUMERIC(12, 2) NOT NULL,
    estado          VARCHAR(30) NOT NULL DEFAULT 'pendiente',
    metodo_pago     VARCHAR(40),
    fecha_venta     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ventas_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_ventas_producto
        FOREIGN KEY (producto_id) REFERENCES productos (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_ventas_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_ventas_precio CHECK (precio_unitario >= 0),
    CONSTRAINT ck_ventas_total CHECK (total >= 0),
    CONSTRAINT ck_ventas_estado CHECK (
        estado IN ('pendiente', 'completado', 'cancelado', 'reembolsado')
    )
);

CREATE INDEX idx_ventas_usuario ON ventas (usuario_id);
CREATE INDEX idx_ventas_producto ON ventas (producto_id);
CREATE INDEX idx_ventas_fecha ON ventas (fecha_venta);

COMMENT ON TABLE ventas IS 'Transacciones de venta; alineado con Venta.java del backend';
