CREATE TABLE productos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    precio DOUBLE PRECISION,
    categoria VARCHAR(255),
    descripcion VARCHAR(255),
    fecha_creacion TIMESTAMP
);

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    nombre VARCHAR(255),
    fecha_registro TIMESTAMP,
    activo BOOLEAN,
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);
