-- V1: Usuarios del sistema (login JWT, roles)
CREATE TABLE usuarios (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(120) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    rol             VARCHAR(20) NOT NULL DEFAULT 'USER',
    fecha_registro  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('USER', 'ADMIN'))
);

COMMENT ON TABLE usuarios IS 'Cuentas de acceso a la API';
COMMENT ON COLUMN usuarios.password IS 'Hash BCrypt; nunca texto plano';
